# Generated by Django 5.2.5 on 2025-08-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id'], 'verbose_name': '零部件', 'verbose_name_plural': '零部件'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['id'], 'verbose_name': '车型信息', 'verbose_name_plural': '车型信息'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='component',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='testproject',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='updated_at',
        ),
    ]
