# Generated by Django 5.2.5 on 2025-09-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0004_airtightnessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='energy_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='能源形式'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='seat_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='座位数'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='sunroof_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='天窗形式'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='suspension_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='悬挂形式'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='cle_model_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='车型代码'),
        ),
    ]
