# Generated by Django 5.2.5 on 2025-09-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0005_remove_component_component_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_code',
        ),
    ]
