# Generated by Django 5.2.5 on 2025-10-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0006_remove_component_component_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtightnessimage',
            options={'ordering': ['-id'], 'verbose_name': '气密性测试图片', 'verbose_name_plural': '气密性测试图片'},
        ),
        migrations.AlterModelOptions(
            name='airtightnesstest',
            options={'ordering': ['-id'], 'verbose_name': '气密性测试', 'verbose_name_plural': '气密性测试'},
        ),
        migrations.AlterModelOptions(
            name='modaldata',
            options={'ordering': ['-id'], 'verbose_name': '模态数据', 'verbose_name_plural': '模态数据'},
        ),
        migrations.AlterModelOptions(
            name='testproject',
            options={'ordering': ['-id'], 'verbose_name': '测试项目', 'verbose_name_plural': '测试项目'},
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modaldata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='testproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testproject',
            name='updated_at',
        ),
    ]
