# Generated by Django 5.2.3 on 2025-10-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0007_alter_airtightnessimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproject',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='测试日期'),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='test_engineer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试工程师'),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='test_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='测试类型'),
        ),
    ]
