# Generated by Django 5.2.3 on 2025-10-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0008_alter_testproject_test_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modaldata',
            name='updated_by',
        ),
    ]
