# Generated by Django 5.2.3 on 2025-11-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0009_remove_modaldata_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtightnessimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airtightnessimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='airtightnesstest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airtightnesstest',
            name='updated_at',
        ),
    ]
