# Generated by Django 5.2.3 on 2025-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0010_remove_airtightnessimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtightnessimage',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='airtightnessimage',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='测试日期'),
        ),
        migrations.AddField(
            model_name='airtightnessimage',
            name='test_engineer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试工程师'),
        ),
        migrations.AddField(
            model_name='airtightnessimage',
            name='test_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='测试地点'),
        ),
    ]
