# Generated by Django 5.2.3 on 2025-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0011_remove_airtightnessimage_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='front_windshield',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='前挡玻璃'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='side_door_glass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='侧门玻璃'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='subframe_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='副车架形式'),
        ),
    ]
