# Generated by Django 5.2.3 on 2025-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0012_vehiclemodel_front_windshield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaldata',
            name='damping_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='阻尼比'),
        ),
    ]
