# Generated by Django 5.2.3 on 2025-12-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0014_vehiclemodel_benchmark_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtightnessimage',
            name='door_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='airtightness/', verbose_name='车门图片路径'),
        ),
        migrations.AlterField(
            model_name='airtightnessimage',
            name='front_compartment_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='airtightness/', verbose_name='前舱图片路径'),
        ),
        migrations.AlterField(
            model_name='airtightnessimage',
            name='tailgate_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='airtightness/', verbose_name='尾门图片路径'),
        ),
    ]
