# Generated by Django 5.2.5 on 2025-09-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modal', '0004_airtightnessimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTFInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=50, verbose_name='测试人员')),
                ('test_time', models.DateTimeField(verbose_name='测试时间')),
                ('location', models.CharField(max_length=100, verbose_name='测试地点')),
                ('sunroof_type', models.CharField(max_length=50, verbose_name='天窗形式')),
                ('suspension_type', models.CharField(max_length=50, verbose_name='悬挂形式')),
                ('seat_count', models.PositiveSmallIntegerField(verbose_name='座位数')),
                ('front_row_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='前排测试图片路径')),
                ('middle_row_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='中排测试图片路径')),
                ('rear_row_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='后排测试图片路径')),
                ('development_stage', models.CharField(max_length=50, verbose_name='开发阶段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntf_infos', to='modal.vehiclemodel', verbose_name='车型信息')),
            ],
            options={
                'verbose_name': 'NTF测试信息',
                'verbose_name_plural': 'NTF测试信息',
                'db_table': 'NTF_info',
                'ordering': ['-test_time'],
            },
        ),
        migrations.CreateModel(
            name='NTFTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_point', models.CharField(max_length=100, verbose_name='测点')),
                ('direction', models.CharField(choices=[('X', 'X方向'), ('Y', 'Y方向'), ('Z', 'Z方向')], max_length=1, verbose_name='方向')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='目标值(dB)')),
                ('front_row_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='前排值(dB)')),
                ('middle_row_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='中排值(dB)')),
                ('rear_row_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='后排值(dB)')),
                ('ntf_curve', models.JSONField(default=dict, verbose_name='NTF原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ntf_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='NTF.ntfinfo', verbose_name='NTF信息')),
            ],
            options={
                'verbose_name': 'NTF测试结果',
                'verbose_name_plural': 'NTF测试结果',
                'db_table': 'NTF_test_result',
                'ordering': ['measurement_point', 'direction'],
                'unique_together': {('ntf_info', 'measurement_point', 'direction')},
            },
        ),
    ]
