# Generated by Django 5.2.3 on 2025-10-09 08:31

import apps.NTF.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modal', '0006_remove_component_component_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTFInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=50, verbose_name='测试人员')),
                ('test_time', models.DateTimeField(verbose_name='测试时间')),
                ('location', models.CharField(max_length=100, verbose_name='测试地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntf_infos', to='modal.vehiclemodel', verbose_name='车型信息')),
            ],
            options={
                'verbose_name': 'NTF测试信息',
                'verbose_name_plural': 'NTF测试信息',
                'db_table': 'NTF_info',
                'ordering': ['-test_time'],
            },
        ),
        migrations.CreateModel(
            name='NTFTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_point', models.CharField(max_length=100, verbose_name='测点')),
                ('layout_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='测点布置图URL')),
                ('ntf_curve', models.JSONField(blank=True, default=apps.NTF.models._default_ntf_curve, verbose_name='NTF曲线数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ntf_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='NTF.ntfinfo', verbose_name='NTF信息')),
            ],
            options={
                'verbose_name': 'NTF测试结果',
                'verbose_name_plural': 'NTF测试结果',
                'db_table': 'NTF_test_result',
                'ordering': ['measurement_point'],
                'unique_together': {('ntf_info', 'measurement_point')},
            },
        ),
    ]
