# Generated by Django 5.2.5 on 2025-10-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntfinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ntfinfo',
            name='updated_at',
        ),
    ]
