# Generated by Django 5.2.5 on 2025-10-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0002_remove_ntfinfo_created_at_remove_ntfinfo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntftestresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ntftestresult',
            name='updated_at',
        ),
    ]
