# Generated by Django 5.2.3 on 2025-10-16 02:18

import apps.NTF.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0003_remove_ntftestresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntfinfo',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='测试地点'),
        ),
        migrations.AlterField(
            model_name='ntfinfo',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测试时间'),
        ),
        migrations.AlterField(
            model_name='ntfinfo',
            name='tester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试人员'),
        ),
        migrations.AlterField(
            model_name='ntftestresult',
            name='measurement_point',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='测点'),
        ),
        migrations.AlterField(
            model_name='ntftestresult',
            name='ntf_curve',
            field=models.JSONField(blank=True, default=apps.NTF.models._default_ntf_curve, null=True, verbose_name='NTF曲线数据'),
        ),
    ]
