# Generated by Django 5.2.3 on 2025-11-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0005_remove_unique_together_ntftestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntfinfo',
            name='test_time',
            field=models.DateField(blank=True, null=True, verbose_name='测试日期'),
        ),
    ]
