# Generated by Django 5.2.5 on 2025-09-23 08:32

import apps.NTF.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0007_drop_xyz_curve_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntftestresult',
            name='layout_image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='测点布置图URL'),
        ),
        migrations.AlterField(
            model_name='ntftestresult',
            name='ntf_curve',
            field=models.JSONField(blank=True, default=apps.NTF.models._default_ntf_curve, verbose_name='NTF原始数据'),
        ),
    ]
