# Generated by Django 5.2.5 on 2025-09-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NTF', '0009_remove_ntfinfo_row_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntfinfo',
            name='development_stage',
        ),
        migrations.RemoveField(
            model_name='ntfinfo',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='ntfinfo',
            name='sunroof_type',
        ),
        migrations.RemoveField(
            model_name='ntfinfo',
            name='suspension_type',
        ),
    ]
