# 第一阶段：构建前端
FROM node:18-alpine as build-stage

WORKDIR /app
RUN npm config set registry https://registry.npmmirror.com

# 复制依赖文件
COPY package*.json ./

# 安装全量依赖（包含devDependencies）
RUN npm ci

# 复制源代码
COPY . .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

# 运行Vite构建
RUN npm run build

# 第二阶段：运行
FROM nginx:1.21-alpine

COPY --from=build-stage /app/dist /var/www/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
