# Generated by Django 5.2.3 on 2025-09-22 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modal', '0004_airtightnessimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_brand', models.CharField(max_length=100, verbose_name='轮胎品牌')),
                ('tire_model', models.CharField(max_length=100, verbose_name='轮胎型号')),
                ('is_silent', models.BooleanField(default=False, verbose_name='是否静音轮胎')),
                ('rim_material', models.CharField(max_length=100, verbose_name='轮辋材质')),
                ('rim_mass_mt', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='轮辋质量 M_T (kg)')),
                ('resonance_peak_f1', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='共振峰 f1 (Hz)')),
                ('anti_resonance_peak_f2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='反共振峰 f2 (Hz)')),
                ('rim_lateral_stiffness', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='轮辋侧向刚度 (kN/mm)')),
                ('rim_stiffness_curve_url', models.CharField(max_length=255, verbose_name='轮辋刚度曲线图 URL')),
                ('rim_stiffness_test_image_url', models.CharField(max_length=255, verbose_name='轮辋刚度测试图 URL')),
                ('force_transfer_first_peak', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='力传递率第一阶峰值')),
                ('force_transfer_test_image_url', models.CharField(max_length=255, verbose_name='力传递率测试图 URL')),
                ('force_transfer_signal', models.JSONField(default=list, verbose_name='力传递率第一阶详细信号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_performances', to='modal.vehiclemodel', verbose_name='车型信息')),
            ],
            options={
                'verbose_name': '轮胎性能',
                'verbose_name_plural': '轮胎性能',
                'db_table': 'wheel_performance',
                'ordering': ['vehicle_model__vehicle_model_name', 'tire_brand', 'tire_model'],
            },
        ),
    ]
