# Generated by Django 5.2.5 on 2025-09-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelperformance',
            options={'ordering': ['vehicle_model__vehicle_model_name', 'tire_brand', 'tire_model'], 'verbose_name': '车轮性能', 'verbose_name_plural': '车轮性能'},
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_first_peak',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='力传递一阶峰值'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_signal',
            field=models.JSONField(default=list, verbose_name='力传递一阶曲线信号'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_test_image_url',
            field=models.CharField(max_length=255, verbose_name='力传递测试图 URL'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='is_silent',
            field=models.BooleanField(default=False, verbose_name='是否静音胎'),
        ),
    ]
