# Generated by Django 5.2.3 on 2025-12-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_performance', '0002_alter_wheelperformance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelperformance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wheelperformance',
            name='updated_at',
        ),
    ]
