# Generated by Django 5.2.3 on 2025-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_performance', '0003_remove_wheelperformance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelperformance',
            name='anti_resonance_peak_f2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='反共振峰 f2 (Hz)'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_first_peak',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='力传递一阶峰值'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_signal',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='力传递一阶曲线信号'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='force_transfer_test_image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='力传递测试图 URL'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='is_silent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否静音胎'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='resonance_peak_f1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='共振峰 f1 (Hz)'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='rim_lateral_stiffness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='轮辋侧向刚度 (kN/mm)'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='rim_mass_mt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='轮辋质量 M_T (kg)'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='rim_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='轮辋材质'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='rim_stiffness_curve_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='轮辋刚度曲线图 URL'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='rim_stiffness_test_image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='轮辋刚度测试图 URL'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='tire_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='轮胎品牌'),
        ),
        migrations.AlterField(
            model_name='wheelperformance',
            name='tire_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='轮胎型号'),
        ),
    ]
