# Generated by Django 5.2.5 on 2025-09-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0001_initial'),
        ('modal', '0004_airtightnessimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMountIsolationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='测试时间')),
                ('test_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试地点')),
                ('test_engineer', models.CharField(max_length=50, verbose_name='测试人员')),
                ('suspension_type', models.CharField(max_length=50, verbose_name='悬挂形式')),
                ('tire_pressure', models.CharField(blank=True, max_length=50, null=True, verbose_name='实测胎压')),
                ('seat_vib_x_ac_off', models.FloatField(blank=True, null=True, verbose_name='座椅导轨X方向振动 AC OFF')),
                ('seat_vib_y_ac_off', models.FloatField(blank=True, null=True, verbose_name='座椅导轨Y方向振动 AC OFF')),
                ('seat_vib_z_ac_off', models.FloatField(blank=True, null=True, verbose_name='座椅导轨Z方向振动 AC OFF')),
                ('seat_vib_x_ac_on', models.FloatField(blank=True, null=True, verbose_name='座椅导轨X方向振动 AC ON')),
                ('seat_vib_y_ac_on', models.FloatField(blank=True, null=True, verbose_name='座椅导轨Y方向振动 AC ON')),
                ('seat_vib_z_ac_on', models.FloatField(blank=True, null=True, verbose_name='座椅导轨Z方向振动 AC ON')),
                ('steering_vib_x_ac_off', models.FloatField(blank=True, null=True, verbose_name='方向盘X方向振动 AC OFF')),
                ('steering_vib_y_ac_off', models.FloatField(blank=True, null=True, verbose_name='方向盘Y方向振动 AC OFF')),
                ('steering_vib_z_ac_off', models.FloatField(blank=True, null=True, verbose_name='方向盘Z方向振动 AC OFF')),
                ('steering_vib_x_ac_on', models.FloatField(blank=True, null=True, verbose_name='方向盘X方向振动 AC ON')),
                ('steering_vib_y_ac_on', models.FloatField(blank=True, null=True, verbose_name='方向盘Y方向振动 AC ON')),
                ('steering_vib_z_ac_on', models.FloatField(blank=True, null=True, verbose_name='方向盘Z方向振动 AC ON')),
                ('cabin_noise_front_ac_off', models.FloatField(blank=True, null=True, verbose_name='前排内噪 AC OFF')),
                ('cabin_noise_rear_ac_off', models.FloatField(blank=True, null=True, verbose_name='后排内噪 AC OFF')),
                ('cabin_noise_front_ac_on', models.FloatField(blank=True, null=True, verbose_name='前排内噪 AC ON')),
                ('cabin_noise_rear_ac_on', models.FloatField(blank=True, null=True, verbose_name='后排内噪 AC ON')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modal.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '整车悬置隔振率测试',
                'verbose_name_plural': '整车悬置隔振率测试',
                'db_table': 'vehicle_mount_isolation_tests',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='MountIsolationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_point', models.CharField(max_length=100, verbose_name='测点名称')),
                ('x_ac_off_isolation', models.FloatField(blank=True, null=True, verbose_name='X方向AC OFF隔振率(dB)')),
                ('x_ac_off_vibration', models.FloatField(blank=True, null=True, verbose_name='X方向AC OFF 2阶被动端振动(m/s²)')),
                ('x_ac_on_isolation', models.FloatField(blank=True, null=True, verbose_name='X方向AC ON隔振率(dB)')),
                ('x_ac_on_vibration', models.FloatField(blank=True, null=True, verbose_name='X方向AC ON 2阶被动端振动(m/s²)')),
                ('y_ac_off_isolation', models.FloatField(blank=True, null=True, verbose_name='Y方向AC OFF隔振率(dB)')),
                ('y_ac_off_vibration', models.FloatField(blank=True, null=True, verbose_name='Y方向AC OFF 2阶被动端振动(m/s²)')),
                ('y_ac_on_isolation', models.FloatField(blank=True, null=True, verbose_name='Y方向AC ON隔振率(dB)')),
                ('y_ac_on_vibration', models.FloatField(blank=True, null=True, verbose_name='Y方向AC ON 2阶被动端振动(m/s²)')),
                ('z_ac_off_isolation', models.FloatField(blank=True, null=True, verbose_name='Z方向AC OFF隔振率(dB)')),
                ('z_ac_off_vibration', models.FloatField(blank=True, null=True, verbose_name='Z方向AC OFF 2阶被动端振动(m/s²)')),
                ('z_ac_on_isolation', models.FloatField(blank=True, null=True, verbose_name='Z方向AC ON隔振率(dB)')),
                ('z_ac_on_vibration', models.FloatField(blank=True, null=True, verbose_name='Z方向AC ON 2阶被动端振动(m/s²)')),
                ('layout_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试布置图路径')),
                ('curve_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据曲线图路径')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_stiffness.vehiclemountisolationtest', verbose_name='测试基本信息')),
            ],
            options={
                'verbose_name': '悬置隔振率试验数据',
                'verbose_name_plural': '悬置隔振率试验数据',
                'db_table': 'mount_isolation_data',
                'ordering': ['measuring_point'],
            },
        ),
    ]
