# Generated by Django 5.2.3 on 2025-09-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0002_vehiclemountisolationtest_mountisolationdata'),
        ('modal', '0004_airtightnessimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSuspensionIsolationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='测试时间')),
                ('test_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试地点')),
                ('test_engineer', models.CharField(max_length=50, verbose_name='测试人员')),
                ('suspension_type', models.CharField(max_length=50, verbose_name='悬挂形式')),
                ('tire_pressure', models.CharField(blank=True, max_length=50, null=True, verbose_name='实测胎压')),
                ('test_condition', models.CharField(blank=True, max_length=200, null=True, verbose_name='测试工况')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modal.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '整车悬架隔振率测试',
                'verbose_name_plural': '整车悬架隔振率测试',
                'db_table': 'vehicle_suspension_isolation_tests',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='SuspensionIsolationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_point', models.CharField(max_length=100, verbose_name='测点名称')),
                ('x_active_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='X方向主动端(m/s²)')),
                ('x_passive_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='X方向被动端(m/s²)')),
                ('x_isolation_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='X方向隔振率(dB)')),
                ('y_active_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Y方向主动端(m/s²)')),
                ('y_passive_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Y方向被动端(m/s²)')),
                ('y_isolation_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Y方向隔振率(dB)')),
                ('z_active_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Z方向主动端(m/s²)')),
                ('z_passive_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Z方向被动端(m/s²)')),
                ('z_isolation_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Z方向隔振率(dB)')),
                ('layout_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试布置图路径')),
                ('curve_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据曲线图路径')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_stiffness.vehiclesuspensionisolationtest', verbose_name='测试基本信息')),
            ],
            options={
                'verbose_name': '悬架隔振率试验数据',
                'verbose_name_plural': '悬架隔振率试验数据',
                'db_table': 'suspension_isolation_data',
                'ordering': ['measuring_point'],
            },
        ),
    ]
