# Generated by Django 5.2.3 on 2025-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0003_vehiclesuspensionisolationtest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicstiffnesstest',
            name='suspension_type',
        ),
        migrations.AlterField(
            model_name='dynamicstiffnesstest',
            name='analysis_engineer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分析人员'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnesstest',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='测试时间'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnesstest',
            name='test_engineer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试人员'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnesstest',
            name='test_photo_path',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='测试照片路径'),
        ),
    ]
