# Generated by Django 5.2.3 on 2025-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0003_vehiclesuspensionisolationtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_63_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='63Hz X方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_63_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='63Hz Y方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_63_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='63Hz Z方向'),
        ),
    ]
