# Generated by Django 5.2.3 on 2025-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0005_remove_dynamicstiffnesstest_suspension_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_160_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='160Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_160_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='160Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_160_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='160Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_315_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='315Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_315_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='315Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_315_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='315Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_63_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='63Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_63_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='63Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_63_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='63Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X方向目标值'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y方向目标值'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z方向目标值'),
        ),
    ]
