# Generated by Django 5.2.3 on 2025-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0005_remove_dynamicstiffnesstest_suspension_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_160_x',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_160_y',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_160_z',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_315_x',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_315_y',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_315_z',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_63_x',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_63_y',
        ),
        migrations.RemoveField(
            model_name='dynamicstiffnessdata',
            name='freq_63_z',
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_120_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='120Hz X方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_120_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='120Hz Y方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_120_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='120Hz Z方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_23_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='23Hz X方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_23_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='23Hz Y方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_23_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='23Hz Z方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_310_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='310Hz X方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_310_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='310Hz Y方向'),
        ),
        migrations.AddField(
            model_name='dynamicstiffnessdata',
            name='freq_310_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='310Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_100_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='100Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_125_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='125Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_200_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='200Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_250_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='250Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_350_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='350Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_400_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='400Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_50_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='50Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz X方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz Y方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='freq_80_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='80Hz Z方向'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X方向目标值'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y方向目标值'),
        ),
        migrations.AlterField(
            model_name='dynamicstiffnessdata',
            name='target_stiffness_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z方向目标值'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='x_active_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X方向主动端(m/s²)'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='x_passive_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X方向被动端(m/s²)'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='y_active_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y方向主动端(m/s²)'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='y_passive_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y方向被动端(m/s²)'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='z_active_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z方向主动端(m/s²)'),
        ),
        migrations.AlterField(
            model_name='suspensionisolationdata',
            name='z_passive_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z方向被动端(m/s²)'),
        ),
    ]
