# Generated by Django 5.2.3 on 2025-11-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0007_remove_suspension_type_from_mount_and_suspension_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='curve_image_path',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='x_ac_off_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='x_ac_off_vibration',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='x_ac_on_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='x_ac_on_vibration',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='y_ac_off_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='y_ac_off_vibration',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='y_ac_on_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='y_ac_on_vibration',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='z_ac_off_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='z_ac_off_vibration',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='z_ac_on_isolation',
        ),
        migrations.RemoveField(
            model_name='mountisolationdata',
            name='z_ac_on_vibration',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='cabin_noise_front_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='cabin_noise_front_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='cabin_noise_rear_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='cabin_noise_rear_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_x_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_x_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_y_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_y_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_z_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='seat_vib_z_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_x_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_x_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_y_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_y_ac_on',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_z_ac_off',
        ),
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='steering_vib_z_ac_on',
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='speed_or_rpm',
            field=models.JSONField(blank=True, null=True, verbose_name='速度或者转速'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='x_active',
            field=models.JSONField(blank=True, null=True, verbose_name='X方向主动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='x_isolation',
            field=models.JSONField(blank=True, null=True, verbose_name='X方向隔振率(dB)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='x_passive',
            field=models.JSONField(blank=True, null=True, verbose_name='X方向被动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='y_active',
            field=models.JSONField(blank=True, null=True, verbose_name='Y方向主动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='y_isolation',
            field=models.JSONField(blank=True, null=True, verbose_name='Y方向隔振率(dB)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='y_passive',
            field=models.JSONField(blank=True, null=True, verbose_name='Y方向被动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='z_active',
            field=models.JSONField(blank=True, null=True, verbose_name='Z方向主动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='z_isolation',
            field=models.JSONField(blank=True, null=True, verbose_name='Z方向隔振率(dB)'),
        ),
        migrations.AddField(
            model_name='mountisolationdata',
            name='z_passive',
            field=models.JSONField(blank=True, null=True, verbose_name='Z方向被动端振动(m/s²)'),
        ),
        migrations.AddField(
            model_name='vehiclemountisolationtest',
            name='energy_type',
            field=models.IntegerField(choices=[(0, '燃油'), (1, '纯电/混动')], default=0, verbose_name='能源类型'),
        ),
        migrations.AddField(
            model_name='vehiclemountisolationtest',
            name='test_condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='测试工况'),
        ),
        migrations.AlterField(
            model_name='mountisolationdata',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_data', to='dynamic_stiffness.vehiclemountisolationtest', verbose_name='测试基本信息'),
        ),
        migrations.AlterField(
            model_name='vehiclemountisolationtest',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='测试时间'),
        ),
    ]
