# Generated by Django 5.2.3 on 2025-11-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_stiffness', '0008_remove_mountisolationdata_curve_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemountisolationtest',
            name='tire_pressure',
        ),
    ]
