# Generated by Django 5.2.3 on 2026-01-04 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='接收人')),
                ('enter_time', models.DateTimeField(blank=True, null=True, verbose_name='进入时间')),
                ('purpose', models.CharField(blank=True, default='测试', max_length=100, null=True, verbose_name='用途')),
                ('dispose_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='报废/归还类型')),
                ('disposer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='报废/归还人姓名')),
                ('dispose_time', models.DateTimeField(blank=True, null=True, verbose_name='报废/归还时间')),
                ('return_receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='归还接受人')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=20, verbose_name='表单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆及零件进出登记',
                'verbose_name_plural': '车辆及零件进出登记',
            },
        ),
        migrations.CreateModel(
            name='TestProcessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('test_process_name', models.CharField(max_length=200, verbose_name='过程记录表名')),
            ],
            options={
                'verbose_name': '试验过程记录表清单',
                'verbose_name_plural': '试验过程记录表清单',
            },
        ),
        migrations.CreateModel(
            name='MainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=100, verbose_name='车型')),
                ('vin_or_part_no', models.CharField(db_index=True, max_length=100, verbose_name='VIN码/零件编号')),
                ('test_name', models.CharField(max_length=200, verbose_name='试验名称')),
                ('warning_system_status', models.CharField(max_length=20, verbose_name='加入预警系统状态')),
                ('requester_name', models.CharField(max_length=100, verbose_name='任务提出人')),
                ('schedule_start', models.DateTimeField(db_index=True, verbose_name='试验安排开始时间')),
                ('schedule_end', models.DateTimeField(blank=True, null=True, verbose_name='试验安排结束时间')),
                ('schedule_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='试验安排时间备注')),
                ('test_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='试验地点')),
                ('tester_name', models.CharField(max_length=100, verbose_name='测试人员')),
                ('contract_no', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='合同编号')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='是否闭环')),
                ('closure_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环判断更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_records', to='nvh_task.entryexit', verbose_name='关联进出登记')),
            ],
            options={
                'verbose_name': '任务主记录',
                'verbose_name_plural': '任务主记录',
            },
        ),
        migrations.CreateModel(
            name='DocApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
                ('doc_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='编号')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='数量')),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='接收人')),
                ('issuer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='发放人')),
                ('approver_name', models.CharField(default='admin', max_length=100, verbose_name='批准人')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发放日期')),
                ('file_url', models.ImageField(blank=True, null=True, upload_to='nvh_task/nvh_task_approval/', verbose_name='文件(图片)')),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=20, verbose_name='表单状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_approval', to='nvh_task.mainrecord', verbose_name='关联主任务')),
            ],
            options={
                'verbose_name': '技术资料发放批准单',
                'verbose_name_plural': '技术资料发放批准单',
            },
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('nvh_lab_mgmt_no', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='NVH试验室管理号')),
                ('sample_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='样品名称')),
                ('rd_stage', models.CharField(blank=True, max_length=20, null=True, verbose_name='研发阶段')),
                ('delivery_dept', models.CharField(blank=True, max_length=200, null=True, verbose_name='送件部门')),
                ('report_required', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否出具试验/不确定度报告')),
                ('report_no', models.CharField(default='/', max_length=100, verbose_name='报告编号')),
                ('include_teardown_record', models.CharField(default='否', max_length=20, verbose_name='是否包含拆装记录表')),
                ('include_process_record', models.CharField(default='否', max_length=20, verbose_name='是否包含试验过程记录表')),
                ('teardown_attachment_url', models.ImageField(blank=True, null=True, upload_to='nvh_task/teardown_record/', verbose_name='拆装记录表附件(图片)')),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=20, verbose_name='表单状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='nvh_task.mainrecord', verbose_name='关联主任务')),
            ],
            options={
                'verbose_name': '试验信息登记',
                'verbose_name_plural': '试验信息登记',
            },
        ),
        migrations.CreateModel(
            name='TestProcessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_name', models.CharField(max_length=200, verbose_name='过程记录表名')),
                ('file_url', models.ImageField(upload_to='nvh_task/nvh_test_process/', verbose_name='图片(过程记录附件)')),
                ('sort_no', models.PositiveIntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_attachments', to='nvh_task.testinfo', verbose_name='关联试验信息')),
            ],
            options={
                'verbose_name': '试验过程记录附件',
                'verbose_name_plural': '试验过程记录附件',
            },
        ),
    ]
