# Generated by Django 5.2.3 on 2026-01-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='nvh_lab_mgmt_no',
        ),
        migrations.RemoveField(
            model_name='testinfo',
            name='report_no',
        ),
        migrations.RemoveField(
            model_name='testinfo',
            name='report_required',
        ),
        migrations.AddField(
            model_name='mainrecord',
            name='report_required',
            field=models.CharField(default='否', max_length=10, verbose_name='是否出具报告'),
        ),
    ]
