# Generated by Django 5.2.3 on 2026-01-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0002_remove_testinfo_nvh_lab_mgmt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrecord',
            name='assistants',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='协助人员'),
        ),
    ]
