# Generated by Django 5.2.3 on 2026-01-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0003_mainrecord_assistants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docapproval',
            name='doc_no',
        ),
        migrations.AlterField(
            model_name='docapproval',
            name='approver_name',
            field=models.CharField(default='秦军旭', max_length=100, verbose_name='批准人'),
        ),
    ]
