# Generated by Django 5.2.3 on 2026-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0004_remove_docapproval_doc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrecord',
            name='doc_requirement',
            field=models.BooleanField(default=False, verbose_name='是否要求技术资料'),
        ),
        migrations.AddField(
            model_name='mainrecord',
            name='task_scenario',
            field=models.CharField(default='NORMAL', max_length=50, verbose_name='任务场景'),
        ),
    ]
