# Generated by Django 5.2.3 on 2026-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0005_mainrecord_doc_requirement_mainrecord_task_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrecord',
            name='tester_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='测试人员'),
        ),
    ]
