# Generated by Django 5.2.3 on 2026-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvh_task', '0006_alter_mainrecord_tester_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRequester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '常用委托人',
                'verbose_name_plural': '常用委托人',
            },
        ),
    ]
