# Generated by Django 5.2.3 on 2025-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('part_name', models.CharField(max_length=100, verbose_name='零件名称')),
                ('development_stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='开发阶段')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('test_order_no', models.CharField(max_length=50, unique=True, verbose_name='检测委托单号')),
                ('sample_no', models.CharField(db_index=True, max_length=50, verbose_name='样品编号')),
                ('sample_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='样品图URL')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='检测时间')),
                ('benzene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯')),
                ('toluene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲苯')),
                ('ethylbenzene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙苯')),
                ('xylene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='二甲苯')),
                ('styrene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯乙烯')),
                ('formaldehyde', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲醛')),
                ('acetaldehyde', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙醛')),
                ('acrolein', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='丙烯醛')),
                ('acetone', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='丙酮')),
                ('tvoc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='TVOC')),
                ('odor_static_front', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='静态-前排')),
                ('odor_static_rear', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='静态-后排')),
                ('odor_dynamic_front', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='动态-前排')),
                ('odor_dynamic_rear', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='动态-后排')),
                ('odor_mean', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='气味均值')),
            ],
            options={
                'verbose_name': '样品信息',
                'verbose_name_plural': '样品信息',
                'db_table': 'voc_sample_info',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['project_name'], name='voc_sample__project_97f4b2_idx'), models.Index(fields=['part_name'], name='voc_sample__part_na_b321aa_idx'), models.Index(fields=['sample_no'], name='voc_sample__sample__6c0e5d_idx'), models.Index(fields=['test_date'], name='voc_sample__test_da_8e59d7_idx')],
            },
        ),
    ]
