# Generated by Django 5.2.3 on 2025-11-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_name_cn', models.CharField(max_length=100, verbose_name='物质中文名')),
                ('substance_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='物质英文名')),
                ('cas_no', models.CharField(max_length=50, unique=True, verbose_name='CAS号')),
                ('substance_type', models.CharField(choices=[('standard', '行标规定'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='物质类型')),
                ('odor_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='嗅阈值(μg/m³)')),
                ('organic_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='有机物阈值')),
                ('limit_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='限值')),
                ('odor_character', models.CharField(blank=True, max_length=200, null=True, verbose_name='气味特性')),
                ('main_usage', models.TextField(blank=True, null=True, verbose_name='主要用途')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '物质库',
                'verbose_name_plural': '物质库',
                'db_table': 'substanceInfo',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['cas_no'], name='substanceIn_cas_no_a20547_idx'), models.Index(fields=['substance_name_cn'], name='substanceIn_substan_607380_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubstancesTestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='浓度(μg/m³)')),
                ('retention_time', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='保留时间')),
                ('match_degree', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='匹配度(%)')),
                ('concentration_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='浓度占比(%)')),
                ('qij', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='气味阈稀释倍数 Qij')),
                ('wih', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='有机物阈稀释倍数 Wih')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_details', to='vehicle_body.sampleinfo', verbose_name='所属样品')),
                ('substance', models.ForeignKey(db_column='cas_no', on_delete=django.db.models.deletion.CASCADE, to='vehicle_body.substance', to_field='cas_no', verbose_name='物质')),
            ],
            options={
                'verbose_name': 'VOC浓度明细',
                'verbose_name_plural': 'VOC浓度明细',
                'db_table': 'substance_test_details',
                'unique_together': {('sample', 'substance')},
            },
        ),
    ]
