# Generated by Django 5.2.3 on 2025-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0002_substance_substancestestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfo',
            name='test_order_no',
            field=models.CharField(max_length=50, verbose_name='检测委托单号'),
        ),
    ]
