# Generated by Django 5.2.3 on 2025-12-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0003_alter_sampleinfo_test_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='substance_name_cn',
            field=models.CharField(max_length=200, verbose_name='物质中文名'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='物质英文名'),
        ),
    ]
