# Generated by Django 5.2.3 on 2025-12-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0004_alter_substance_substance_name_cn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='substance_name_cn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='物质中文名'),
        ),
    ]
