# Generated by Django 5.2.3 on 2025-12-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0006_alter_sampleinfo_sample_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample_image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='voc_sample/', verbose_name='样品图URL'),
        ),
    ]
