# Generated by Django 5.2.3 on 2026-01-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_body', '0007_alter_sampleinfo_sample_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancestestdetail',
            name='match_degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='匹配度(%)'),
        ),
    ]
