# Generated by Django 5.2.3 on 2025-10-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modal', '0006_remove_component_component_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_condition', models.CharField(max_length=100, verbose_name='工况')),
                ('measure_point', models.CharField(max_length=100, verbose_name='测点')),
                ('spectrum_json', models.JSONField(blank=True, null=True, verbose_name='频谱数据JSON')),
                ('oa_json', models.JSONField(blank=True, null=True, verbose_name='总声压级JSON')),
                ('speech_clarity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='语音清晰度')),
                ('rms_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='有效值')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='测试日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoustic_test_data', to='modal.vehiclemodel', verbose_name='车型信息')),
            ],
            options={
                'verbose_name': '声学测试数据',
                'verbose_name_plural': '声学测试数据',
                'db_table': 'test_data_all',
                'ordering': ['vehicle_model_id', 'work_condition', 'measure_point', '-test_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle_model', 'work_condition', 'measure_point'], name='idx_vm_wc_mp'), models.Index(fields=['test_date'], name='idx_test_date')],
            },
        ),
    ]
