# Generated by Django 5.2.3 on 2025-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoustic_analysis', '0003_add_idx_vm_cp_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionmeasurepoint',
            name='measure_type',
            field=models.CharField(choices=[('noise', '噪声'), ('vibration', '振动'), ('speed', '转速')], db_index=True, default='noise', max_length=20, verbose_name='测点类型'),
        ),
        migrations.AddIndex(
            model_name='conditionmeasurepoint',
            index=models.Index(fields=['measure_type'], name='idx_cm_measure_type'),
        ),
    ]
