# Generated by Django 5.2.3 on 2025-11-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoustic_analysis', '0004_conditionmeasurepoint_measure_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicNoiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_id', models.IntegerField(db_index=True, verbose_name='车型ID')),
                ('x_axis_type', models.CharField(choices=[('speed', '车速'), ('rpm', '转速')], db_index=True, max_length=20, verbose_name='横轴类型')),
                ('sound_pressure_curve', models.JSONField(verbose_name='声压级曲线数据')),
                ('speech_clarity_curve', models.JSONField(verbose_name='语音清晰度曲线数据')),
                ('noise_analysis_image', models.CharField(blank=True, max_length=500, verbose_name='噪声分析图路径')),
                ('audio_file', models.CharField(blank=True, max_length=500, verbose_name='音频文件路径(.wav)')),
                ('spectrum_file', models.CharField(blank=True, max_length=500, verbose_name='三维频谱文件路径(.npz)')),
                ('condition_measure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_noise_data', to='acoustic_analysis.conditionmeasurepoint', verbose_name='工况测点')),
            ],
            options={
                'verbose_name': '动态噪声数据',
                'verbose_name_plural': '动态噪声数据',
                'indexes': [models.Index(fields=['vehicle_model_id'], name='idx_dyn_vm'), models.Index(fields=['condition_measure_point'], name='idx_dyn_cmp'), models.Index(fields=['x_axis_type'], name='idx_dyn_x_axis')],
                'unique_together': {('vehicle_model_id', 'condition_measure_point')},
            },
        ),
    ]
