# Generated by Django 5.2.3 on 2025-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoustic_analysis', '0005_dynamicnoisedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicnoisedata',
            name='spectrum_image_path',
            field=models.CharField(blank=True, help_text='存储频谱图的相对路径或URL', max_length=500, null=True, verbose_name='频谱图路径'),
        ),
        migrations.AlterField(
            model_name='dynamicnoisedata',
            name='spectrum_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='三维频谱文件路径(.pptx)'),
        ),
    ]
