# Generated by Django 5.2.5 on 2025-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0003_vehiclereverberationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundAbsorptionCoefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=100, null=True,verbose_name='零件名称')),
                ('material_composition', models.CharField(blank=True, max_length=100, null=True,verbose_name='材料组成')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='材料厂家')),
                ('test_institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试机构')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='厚度(mm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='克重(g/m²)')),
                ('test_value_125', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='125Hz测试值')),
                ('test_value_160', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='160Hz测试值')),
                ('test_value_200', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='200Hz测试值')),
                ('test_value_250', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='250Hz测试值')),
                ('test_value_315', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='315Hz测试值')),
                ('test_value_400', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='400Hz测试值')),
                ('test_value_500', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='500Hz测试值')),
                ('test_value_630', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='630Hz测试值')),
                ('test_value_800', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='800Hz测试值')),
                ('test_value_1000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1000Hz测试值')),
                ('test_value_1250', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1250Hz测试值')),
                ('test_value_1600', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1600Hz测试值')),
                ('test_value_2000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='2000Hz测试值')),
                ('test_value_2500', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='2500Hz测试值')),
                ('test_value_3150', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='3150Hz测试值')),
                ('test_value_4000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='4000Hz测试值')),
                ('test_value_5000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='5000Hz测试值')),
                ('test_value_6300', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='6300Hz测试值')),
                ('test_value_8000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='8000Hz测试值')),
                ('test_value_10000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='10000Hz测试值')),
                ('target_value_125', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='125Hz目标值')),
                ('target_value_160', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='160Hz目标值')),
                ('target_value_200', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='200Hz目标值')),
                ('target_value_250', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='250Hz目标值')),
                ('target_value_315', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='315Hz目标值')),
                ('target_value_400', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='400Hz目标值')),
                ('target_value_500', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='500Hz目标值')),
                ('target_value_630', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='630Hz目标值')),
                ('target_value_800', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='800Hz目标值')),
                ('target_value_1000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1000Hz目标值')),
                ('target_value_1250', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1250Hz目标值')),
                ('target_value_1600', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='1600Hz目标值')),
                ('target_value_2000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='2000Hz目标值')),
                ('target_value_2500', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='2500Hz目标值')),
                ('target_value_3150', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='3150Hz目标值')),
                ('target_value_4000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='4000Hz目标值')),
                ('target_value_5000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='5000Hz目标值')),
                ('target_value_6300', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='6300Hz目标值')),
                ('target_value_8000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='8000Hz目标值')),
                ('target_value_10000', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='10000Hz目标值')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='测试日期')),
                ('test_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试地点')),
                ('test_engineer', models.CharField(blank=True, max_length=50, null=True, verbose_name='测试工程师')),
                ('test_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='测试图片路径')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '吸声系数',
                'verbose_name_plural': '吸声系数',
                'db_table': 'sound_absorption_coefficients',
                'ordering': ['-created_at'],
            },
        ),
    ]
