# Generated by Django 5.2.5 on 2025-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0005_soundinsulationcoefficients'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPorosityFlowResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='零件名称')),
                ('material_composition', models.CharField(max_length=200, verbose_name='材料组成')),
                ('material_manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='材料厂家')),
                ('test_institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试机构')),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='厚度(mm)')),
                ('weight_per_area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='克重(g/m²)')),
                ('density', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='密度(kg/m³)')),
                ('porosity_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='孔隙率(%)')),
                ('porosity_deviation_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='孔隙率偏差(%)')),
                ('flow_resistance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='流阻率(Pa·s/m²)')),
                ('flow_resistance_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='流阻率偏差(Pa·s/m²)')),
                ('test_time', models.DateTimeField(blank=True, null=True, verbose_name='测试时间')),
                ('test_engineer', models.CharField(blank=True, max_length=50, null=True, verbose_name='测试工程师')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料孔隙率流阻',
                'verbose_name_plural': '材料孔隙率流阻',
                'db_table': 'material_porosity_flow_resistance',
                'ordering': ['-created_at'],
            },
        ),
    ]
