# Generated by Django 5.2.3 on 2025-10-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0006_materialporosityflowresistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_1000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1000Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_10000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='10000Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_1250',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1250Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_1600',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1600Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_2000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2000Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_2500',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2500Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_3150',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='3150Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_400',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='400Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_4000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='4000Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_500',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='500Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_5000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='5000Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_630',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='630Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_6300',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='6300Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_800',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='800Hz混响时间(s)'),
        ),
        migrations.AlterField(
            model_name='vehiclereverberationdata',
            name='freq_8000',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='8000Hz混响时间(s)'),
        ),
    ]
