# Generated by Django 5.2.5 on 2025-10-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0007_alter_vehiclereverberationdata_freq_1000_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundinsulationdata',
            options={'ordering': ['-id'], 'verbose_name': '隔声量数据', 'verbose_name_plural': '隔声量数据'},
        ),
        migrations.RemoveField(
            model_name='soundinsulationdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soundinsulationdata',
            name='updated_at',
        ),
    ]
