# Generated by Django 5.2.5 on 2025-10-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0008_alter_soundinsulationdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialporosityflowresistance',
            options={'ordering': ['-id'], 'verbose_name': '材料孔隙率流阻', 'verbose_name_plural': '材料孔隙率流阻'},
        ),
        migrations.AlterModelOptions(
            name='soundabsorptioncoefficients',
            options={'ordering': ['-id'], 'verbose_name': '吸声系数', 'verbose_name_plural': '吸声系数'},
        ),
        migrations.AlterModelOptions(
            name='soundinsulationcoefficients',
            options={'ordering': ['-id'], 'verbose_name': '隔声量系数', 'verbose_name_plural': '隔声量系数'},
        ),
        migrations.AlterModelOptions(
            name='vehiclereverberationdata',
            options={'ordering': ['-id'], 'verbose_name': '车辆混响时间数据', 'verbose_name_plural': '车辆混响时间数据'},
        ),
        migrations.AlterModelOptions(
            name='vehiclesoundinsulationdata',
            options={'ordering': ['-id'], 'verbose_name': '车型隔声量数据', 'verbose_name_plural': '车型隔声量数据'},
        ),
        migrations.RemoveField(
            model_name='materialporosityflowresistance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materialporosityflowresistance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='soundabsorptioncoefficients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soundabsorptioncoefficients',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='soundinsulationcoefficients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soundinsulationcoefficients',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclereverberationdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclereverberationdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehiclesoundinsulationdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiclesoundinsulationdata',
            name='updated_at',
        ),
    ]
