# Generated by Django 5.2.3 on 2025-11-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0010_convert_test_image_path_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesoundinsulationdata',
            name='sound_insulation_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='隔声性能'),
        ),
    ]
