# Generated by Django 5.2.3 on 2025-12-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_module', '0011_vehiclesoundinsulationdata_sound_insulation_performance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundinsulationdata',
            options={'ordering': ['-id'], 'verbose_name': '区域隔声量', 'verbose_name_plural': '区域隔声量'},
        ),
        migrations.AlterModelOptions(
            name='vehiclereverberationdata',
            options={'ordering': ['-id'], 'verbose_name': '整车混响时间', 'verbose_name_plural': '整车混响时间'},
        ),
        migrations.AlterModelOptions(
            name='vehiclesoundinsulationdata',
            options={'ordering': ['-id'], 'verbose_name': '整车隔声量', 'verbose_name_plural': '整车隔声量'},
        ),
        migrations.AlterField(
            model_name='soundinsulationdata',
            name='test_image_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='AreaSoundInsulation/', verbose_name='测试图片路径'),
        ),
    ]
