# Generated by Django 5.2.3 on 2025-10-23 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modal', '0009_remove_modaldata_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='零件名称')),
                ('development_stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='开发阶段')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('test_order_no', models.CharField(max_length=50, verbose_name='检测委托单号')),
                ('sample_no', models.CharField(max_length=50, verbose_name='样品编号')),
                ('sample_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='样品图URL')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modal.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '样品信息',
                'verbose_name_plural': '样品信息',
                'db_table': 'sample_info',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VocResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benzene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯 (mg/m³)')),
                ('toluene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲苯 (mg/m³)')),
                ('ethylbenzene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙苯 (mg/m³)')),
                ('xylene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='二甲苯 (mg/m³)')),
                ('styrene', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯乙烯 (mg/m³)')),
                ('formaldehyde', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲醛 (mg/m³)')),
                ('acetaldehyde', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙醛 (mg/m³)')),
                ('acrolein', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='丙烯醛 (mg/m³)')),
                ('tvoc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='TVOC (mg/m³)')),
                ('test_date', models.DateTimeField(blank=True, null=True, verbose_name='检测时间')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc.sampleinfo', verbose_name='样品')),
            ],
            options={
                'verbose_name': 'VOC检测结果',
                'verbose_name_plural': 'VOC检测结果',
                'db_table': 'voc_result',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sampleinfo',
            index=models.Index(fields=['vehicle_model'], name='sample_info_vehicle_e0bd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleinfo',
            index=models.Index(fields=['sample_no'], name='sample_info_sample__358739_idx'),
        ),
        migrations.AddIndex(
            model_name='vocresult',
            index=models.Index(fields=['sample'], name='voc_result_sample__e1e07d_idx'),
        ),
    ]
