# Generated by Django 5.2.3 on 2025-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocresult',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='检测时间'),
        ),
    ]
