# Generated by Django 5.2.3 on 2025-10-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0004_substance_substancestest_substancestestdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancestestdetail',
            name='concentration',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='浓度(μg/m³)'),
        ),
    ]
