# Generated by Django 5.2.3 on 2025-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0005_alter_substancestestdetail_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancestest',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='检测时间'),
        ),
    ]
