# Generated by Django 5.2.3 on 2025-10-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0006_alter_substancestest_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocodorresult',
            name='acetone',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='丙酮 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='acetaldehyde',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙醛 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='acrolein',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='丙烯醛 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='benzene',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='ethylbenzene',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='乙苯 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='formaldehyde',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲醛 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='styrene',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='苯乙烯 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='toluene',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='甲苯 (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='tvoc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='TVOC (μg/m³)'),
        ),
        migrations.AlterField(
            model_name='vocodorresult',
            name='xylene',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='二甲苯 (μg/m³)'),
        ),
    ]
