# Generated by Django 5.2.3 on 2025-11-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc', '0007_vocodorresult_acetone_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='substancestestdetail',
            new_name='substances__cas_no_43497d_idx',
            old_name='substances__substan_9e683f_idx',
        ),
        migrations.AddField(
            model_name='substance',
            name='substance_type',
            field=models.CharField(choices=[('standard', '行标规定'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='物质类型'),
        ),
        migrations.AlterField(
            model_name='substancestestdetail',
            name='substance',
            field=models.ForeignKey(db_column='cas_no', on_delete=django.db.models.deletion.CASCADE, to='voc.substance', to_field='cas_no', verbose_name='物质'),
        ),
    ]
