# Generated by Django 5.2.3 on 2025-10-14 13:50

import apps.experience.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, verbose_name='问题分类')),
                ('problem_name', models.CharField(max_length=200, verbose_name='问题名称')),
                ('keywords', models.CharField(max_length=500, verbose_name='问题关键字（多个关键字用逗号分隔）')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('problem_media', models.JSONField(blank=True, default=apps.experience.models.default_media, null=True, verbose_name='问题描述图片及视频')),
                ('analysis_content', models.TextField(blank=True, null=True, verbose_name='问题分析内容')),
                ('analysis_media', models.JSONField(blank=True, default=apps.experience.models.default_media, null=True, verbose_name='问题分析图片及视频')),
                ('solution_content', models.TextField(blank=True, null=True, verbose_name='解决方案与措施')),
                ('solution_media', models.JSONField(blank=True, default=apps.experience.models.default_media, null=True, verbose_name='解决方案与措施图片及视频')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '经验',
                'verbose_name_plural': '经验',
                'db_table': 'experience',
                'ordering': ['-create_time', '-id'],
            },
        ),
    ]
